@php
    $brand = tva_setting('content.brand_name', 'serveAI');

    $page = [
        'path' => '/ai-voice-agent',

        'intro' => [
            'An AI voice agent answers phone calls the way a person would: it listens, works out what the caller wants, and replies out loud. Behind the scenes it is a chain — speech recognition turns the caller’s words into text, a language model decides the reply, and speech synthesis speaks it back. How natural it feels depends mostly on how quickly that chain completes.',
            $brand . ' gives your business an AI voice agent for inbound calls. Connect your Twilio account and number, choose a voice — or clone your own from a short recording — and the agent answers from the same knowledge that powers your chat and messaging. Every call is transcribed, any contact details the caller gives become a lead, and calls can be routed to different agents by number, skill or flow.',
            'It is for businesses whose phone rings when nobody can pick up: after hours, during the lunch rush, while you are with another customer. It is not an outbound dialler — the agent answers calls, it does not place sales calls.',
        ],

        'stepsTitle' => 'Putting a voice agent on your phone line',
        'steps' => [
            ['Connect your number', 'Add your own Twilio account and choose which number the agent should answer.'],
            ['Choose the voice', 'Pick a voice, or clone one from a short recording so the agent sounds like your business.'],
            ['Route the calls', 'Send each number to a specific agent, a skill-based group, or a guided flow.'],
            ['Review every call', 'Read the transcript of each call, see which leads it captured, and track the minutes you have used.'],
        ],

        'featuresTitle' => 'Built for real phone calls',
        'features' => [
            ['Natural voices, including yours', 'Speech is generated by a neural voice model, and you can clone a voice from a short audio sample — with the speaker’s consent.'],
            ['Automatic language detection', 'Speech recognition can detect the caller’s language, and the agent answers in the same language.'],
            ['Answers from your information', 'Calls draw on the same website, documents, databases and CRM data as every other channel, so answers stay consistent.'],
            ['Routing per number', 'Give each number its own agent, send it to a pool by skill, or run a guided flow for bookings and triage.'],
            ['Leads from every call', 'Names, numbers, emails and intent mentioned on the call are extracted into the CRM with a lead score.'],
            ['Voice in web chat too', 'Website visitors can talk to the same agent through the chat widget’s microphone and hear spoken replies.'],
        ],

        'casesTitle' => 'Calls a voice agent should take',
        'cases' => [
            ['After-hours calls', 'The calls that used to go to voicemail get an answer, and the details are waiting for you in the morning.'],
            ['Peak-time overflow', 'When every line is busy, routine questions — hours, prices, directions — are answered without a queue.'],
            ['Booking enquiries', 'Collect the caller’s details and preferred time, or book directly when your scheduling system is connected through a skill.'],
            ['Several lines, several agents', 'Run a separate number and agent for each location, brand or department.'],
        ],

        'fit' => [
            'title' => 'Latency, accents and when a person should pick up',
            'html'  => '<p>The honest limit of every voice agent is delay. Each step in the chain takes time, and past roughly a second and a half of silence callers notice. Short, factual calls — opening hours, availability, simple bookings — work well. Long, emotional or complicated calls are still better with a person.</p>'
                     . '<p>Test your own language, accent and typical questions on a trial call before you put the agent on your main line, and give callers a clear route to your team. We explain the pipeline, where delay comes from and what drives cost per minute in <a href="' . url('/blog/ai-voice-agents-how-they-work-cost') . '">how AI voice agents work, and what they cost</a>.</p>',
        ],

        'faqs' => [
            ['What is an AI voice agent?', 'An AI voice agent is software that answers phone calls in a natural voice. It converts the caller’s speech to text, decides a reply with a language model, and speaks it back — handling routine calls without a person on the line.'],
            ['Can the AI voice agent use my own voice?', 'Yes. You can clone a voice from a short audio recording and assign it to an agent. Only clone a voice you have the right to use — your own, or a colleague’s with their permission.'],
            ['Which phone numbers can I use?', 'The voice agent connects through Twilio. You bring your own Twilio account and number, and choose which agent, skill or flow each number is routed to.'],
            ['Does it make outbound calls?', 'No. ' . $brand . '’s voice agent answers inbound calls. It is not an outbound dialler or a cold-calling tool.'],
            ['Which languages can it speak?', 'Speech recognition can detect the caller’s language and the agent replies in kind. Voice output covers many major languages, including English, Arabic, Hindi, Spanish, French, German and Chinese. Test your language on a trial call before going live.'],
            ['How are calls billed?', 'Paid plans include a monthly allowance of phone minutes, counted from the call duration and rounded up to the next minute. Current allowances and overage rates are on the pricing page.'],
        ],

        'related'  => ['/ai-customer-support', '/ai-agents', '/omnichannel-customer-support'],
        'ctaTitle' => 'Hear it answer before your customers do',
        'ctaBody'  => 'Set up an agent on your own data, call it, and decide whether it is good enough for your line.',
    ];
@endphp
@extends('layouts.public', [
    'pageEyebrow'     => 'AI voice agent',
    'pageTitle'       => 'An AI voice agent that <span class="accent">answers every call.</span>',
    'pageSubtitle'    => 'Inbound calls answered 24/7 in a natural voice — even your own — from your business information, with a transcript and a lead record for every call.',
    'seoTitle'        => 'AI Voice Agent for Business Phone Calls | ' . $brand,
    'metaDescription' => 'An AI voice agent that answers your business phone calls 24/7 in a natural voice — even your own — with a transcript and lead record for every call.',
    'breadcrumbs'     => [['name' => 'AI voice agent', 'url' => '/ai-voice-agent']],
    'jsonLd'          => [\App\Support\Schema::software(), \App\Support\Schema::faqPage('/ai-voice-agent', $page['faqs'])],
])

@section('content')
    @include('landing._body')
@endsection
